version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: db
    restart: unless-stopped
    env_file:
      - docker.env
    ports:
      - "5432:5432"
    volumes:
      - secret_notes_postgres:/var/lib/postgresql/data
    networks:
      - secret_notes_network
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - docker.env
    ports:
      - "3000:3000"
    networks:
      - secret_notes_network
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - secret_notes_network

volumes:
  secret_notes_postgres:

networks:
  secret_notes_network: