services:
  postgres:
    image: postgres:17.5
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: securenotes
    expose:
      - 5432
    volumes:
      - secure_notes_postgres:/var/lib/postgresql/data
    networks:
      - secure_notes_network
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - secure_notes_network
    env_file: backend/docker.env
    depends_on:
      - postgres
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - secure_notes_network
    depends_on:
      - backend

volumes:
  secure_notes_postgres:

networks:
  secure_notes_network: