services:
  db:
    image: postgres:17-alpine
    container_name: db
    restart: unless-stopped
    env_file:
      - docker.env
    expose:
      - 5432
    volumes:
      - secret_notes_postgres:/var/lib/postgresql/data
    networks:
      - secret_notes_network
  backend-blue:
    image: ${IMAGE_NAME}
    container_name: backend-blue
    restart: unless-stopped
    env_file:
      - docker.env
    expose:
      - 3000
    networks:
      - secret_notes_network
  frontend-blue:
    image: ${IMAGE_NAME}
    container_name: frontend-blue
    restart: unless-stopped
    expose:
      - 80
    networks:
      - secret_notes_network

volumes:
  secret_notes_postgres:

networks:
  secret_notes_network: