services:
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    env_file:
      - docker.env
    expose:
      - 5432
    volumes:
      - secret_notes_postgres:/var/lib/postgresql/data
    networks:
      - secret_notes_network
  backend-blue:
    image: nick7152/secret-notes-backend:${IMAGE_TAG}
    container_name: backend-blue
    restart: always
    env_file:
      - docker.env
    expose:
      - 3000
    networks:
      - secret_notes_network
    depends_on:
      - db
  frontend-blue:
    image: nick7152/secret-notes-frontend:${IMAGE_TAG}
    container_name: frontend-blue
    restart: always
    expose:
      - 80
    networks:
      - secret_notes_network
    depends_on:
      - backend-blue

volumes:
  secret_notes_postgres:

networks:
  secret_notes_network: