services:
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    env_file:
      - docker.env
    expose:
      - 5432
    volumes:
      - secure_notes_postgres:/var/lib/postgresql/data
    networks:
      - secure_notes_network
  backend-green:
    image: nick7152/secret-notes-backend
    container_name: backend-green
    restart: always
    env_file:
      - docker.env
    expose:
      - 3000
    networks:
      - secure_notes_network
    depends_on:
      - db
  frontend-green:
    image: nick7152/secret-notes-frontend
    container_name: frontend-green
    restart: always
    expose:
      - 80
    networks:
      - secure_notes_network
    depends_on:
      - backend-green

volumes:
  secure_notes_postgres:

networks:
  secure_notes_network: