services:
  postgres:
    image: postgres:alpine
    container_name: db
    restart: always
    env_file:
      - docker.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - 5432
    volumes:
      - secure_notes_postgres:/var/lib/postgresql/data
    networks:
      - secure_notes_network
  backend:
    image: nick7152/secret-notes-backend
    container_name: backend
    restart: always
    env_file:
      - docker.env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    expose:
      - 3000
    networks:
      - secure_notes_network
    depends_on:
      - postgres
  frontend:
    image: nick7152/secret-notes-frontend
    container_name: frontend
    restart: always
    expose:
      - 80
    networks:
      - secure_notes_network
    depends_on:
      - backend

volumes:
  secure_notes_postgres:

networks:
  secure_notes_network: