services:
  db-blue:
    image: postgres:alpine
    container_name: db-blue
    restart: always
    env_file:
      - docker-blue.env
    expose:
      - 5432
    volumes:
      - secure_notes_postgres:/var/lib/postgresql/data
    networks:
      - secure_notes_network
  backend-blue:
    image: nick7152/secret-notes-backend
    container_name: backend-blue
    restart: always
    env_file:
      - docker-blue.env
    expose:
      - 3000
    networks:
      - secure_notes_network
    depends_on:
      - db-blue
  frontend-blue:
    image: nick7152/secret-notes-frontend
    container_name: frontend-blue
    restart: always
    expose:
      - 80
    networks:
      - secure_notes_network
    depends_on:
      - backend-blue

volumes:
  secure_notes_postgres:

networks:
  secure_notes_network: