version: '3'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    depends_on:
      - db
    expose:
      - 9000
    environment:
      SONAR_WEB_JAVA_OPTS: "-Xmx512m -Xms256m"
      SONAR_ES_JAVA_OPTS: "-Xmx512m -Xms256m"
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonarpassword
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      - sonar_qube_network
      - jenkins_jenkins_network

  db:
    image: postgres:alpine
    container_name: sonarqube_db
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpassword
      POSTGRES_DB: sonarqube
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonar_qube_network

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql_data:

networks:
  sonar_qube_network:
  jenkins_jenkins_network:
    external: true
