version: '3.8'

services:
  jenkins:
    image: nick7152/jenkins-docker
    container_name: jenkins
    user: jenkins
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx512m
    expose:
      - 8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network

volumes:
  jenkins_home:

networks:
  jenkins_network: