version: '3'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - jenkins_jenkins_network
      - portainer_portainer_network
      - sonarqube_sonarqube_network
      - proxy_network
  blue-green-proxy:
    image: nginx:1.29.0-alpine
    container_name: blue-green-proxy
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - /opt/CONINT/stacks/reverse_proxy/nginx/conf.d/:/etc/nginx/conf.d/
      - /opt/CONINT/stacks/reverse_proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - secret_notes_secret_notes_network
      - proxy_network

networks:
  secret_notes_secret_notes_network:
    external: true
  jenkins_jenkins_network:
    external: true
  portainer_portainer_network:
    external: true
  sonarqube_sonarqube_network:
    external: true
  proxy_network: