name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      dockerhub-repository:
        required: true
        type: string
      image-artifact-name:
        required: true
        type: string

env:
  DOCKERHUB_USERNAME: renerumetshofer

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.image-tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Docker image tag
        id: tag
        run: echo "image-tag=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.dockerhub-repository }}:${{ steps.tag.outputs.image-tag }} ${{ inputs.working-directory }}
      - name: Save Docker image to file
        run: |
          docker save ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.dockerhub-repository }}:${{ steps.tag.outputs.image-tag }} -o image.tar
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image-artifact-name }}
          path: image.tar

  push-backend-image:
    name: Push Docker Image
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.image-artifact-name }}
          path: .
      - name: Load Docker image
        run: |
          docker load -i image.tar
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.dockerhub-repository }}:${{ needs.build-image.outputs.image-tag }} \
                     ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.dockerhub-repository }}:latest
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.dockerhub-repository }}:${{ needs.build-image.outputs.image-tag }}
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.dockerhub-repository }}:latest
