name: Pipeline

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - build

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/backend

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  vulnerability_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: snyk/actions/setup@master
      - uses: actions/setup-node@v4
      - name: Snyk monitor
        run: snyk monitor --all-projects --org=${{ secrets.SNYK_ORG }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk test
        run: snyk test --all-projects --org=${{ secrets.SNYK_ORG }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  test-backend:
    runs-on: ubuntu-latest
    needs: [ sast, vulnerability_scan ]
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run test -- --coverage
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: backend/coverage/lcov-report

#  test-frontend:
#    runs-on: ubuntu-latest
#    needs: [ sast, vulnerability_scan ]
#    defaults:
#      run:
#        working-directory: frontend
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#      - run: npm ci
#      - run: npm run test -- --coverage
#      - name: Archive code coverage results
#        uses: actions/upload-artifact@v4
#        with:
#          name: frontend-coverage-report
#          path: frontend/coverage/lcov-report

  build-backend-image:
    uses: ./.github/workflows/build-and-deliver.yml
    with:
      working-directory: backend
      dockerhub-repository: conint-securenotes-backend
      image-artifact-name: backend-image