name: SSH

on:
  push:
    branches:
      - ssh

jobs:
  deploy-green:
    name: Deploy new Green version
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.image-tag }}
    steps:
      - name: Get commit SHA
        id: tag
        run: echo "image-tag=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
      - name: Deploy new green version
        uses: appleboy/ssh-action@v1
        env:
          GREEN_BACKEND_TAG: ${{ steps.tag.outputs.image-tag }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_HOST_USERNAME }}
          key: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          envs: GREEN_BACKEND_TAG
          script: |
            cd deployment
            sed -i "s/^GREEN_BACKEND_TAG=.*/GREEN_BACKEND_TAG=${GREEN_BACKEND_TAG}/" .env
            docker-compose pull green
            docker-compose up -d green

  switch-green-blue:
    name: Switch from Blue to Green
    runs-on: ubuntu-latest
    needs: deploy-green
    steps:
      - name: Switch from Blue to Green
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_HOST_USERNAME }}
          key: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          script: |
            cd deployment/nginx/conf.d
            rm -f prod.conf
            ln -s green.conf prod.conf
            docker exec blue-green-proxy nginx -s reload

  update-blue:
    name: Update Blue version and switch back to Blue
    runs-on: ubuntu-latest
    needs: switch-green-blue
    steps:
      - name: Update Blue version
        uses: appleboy/ssh-action@v1
        env:
          BLUE_BACKEND_TAG: ${{ needs.deploy-green.outputs.image-tag }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_HOST_USERNAME }}
          key: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          envs: BLUE_BACKEND_TAG
          script: |
            sleep 30
            cd deployment
            sed -i "s/^BLUE_BACKEND_TAG=.*/BLUE_BACKEND_TAG=${BLUE_BACKEND_TAG}/" .env
            docker-compose pull blue
            docker-compose up -d blue
      - name: Switch back to Blue
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_HOST_USERNAME }}
          key: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          script: |
            cd deployment/nginx/conf.d
            rm -f prod.conf
            ln -s blue.conf prod.conf
            docker exec blue-green-proxy nginx -s reload